#! /bin/sh
url="https://api.github.com/search/repositories?q=language:go&sort=stars&per_page=${1-10}"
exec curl -s $url | jq '.items[] | .clone_url' | sed -e 's|^"https://||'  -e 's/.git"$//' | grep -v 'github.com/astaxie/build-web-application-with-golang' | grep -v 'github.com/golang/go'
